/*
 * XYOS V4.5 — 数据库方言适配层
 * 支持 SQLite（默认）/ 达梦 DM8 / 金仓 KingbaseES V9
 * 通过环境变量 DB_DIALECT 切换，默认 sqlite
 * 
 * 向后兼容：当使用 sqlite 时，所有操作委托给现有的 db.ts
 * 国产数据库：通过适配器模式翻译 SQL 方言差异
 */

export type DbDialect = 'sqlite' | 'dameng' | 'kingbase' | 'postgres';

export interface DbAdapterConfig {
  dialect: DbDialect;
  host?: string;
  port?: number;
  database?: string;
  username?: string;
  password?: string;
  // 达梦/金仓 特有配置
  schema?: string;
  connectionTimeout?: number;
}

export interface QueryResult {
  rows: Record<string, unknown>[];
  rowCount: number;
  lastInsertId?: number;
}

export interface DbAdapter {
  dialect: DbDialect;
  connect(): Promise<void>;
  disconnect(): Promise<void>;
  query(sql: string, params?: unknown[]): Promise<QueryResult>;
  execute(sql: string, params?: unknown[]): Promise<QueryResult>;
  // 批量操作
  batch(statements: Array<{ sql: string; params?: unknown[] }>): Promise<void>;
  // 事务
  beginTransaction(): Promise<void>;
  commit(): Promise<void>;
  rollback(): Promise<void>;
  // 工具
  isConnected(): boolean;
  escapeIdentifier(name: string): string;
  getPlaceholder(index: number): string;
}

/**
 * 从环境变量读取数据库配置
 */
export function loadDbConfig(): DbAdapterConfig {
  const dialect = (process.env.DB_DIALECT || 'sqlite') as DbDialect;

  const config: DbAdapterConfig = {
    dialect,
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT || '0', 10),
    database: process.env.DB_NAME || 'xyos',
    username: process.env.DB_USER || 'xyos',
    password: process.env.DB_PASS || '',
    schema: process.env.DB_SCHEMA || 'XYOS',
    connectionTimeout: parseInt(process.env.DB_TIMEOUT || '10000', 10),
  };

  // 根据方言设置默认端口
  if (!config.port || config.port === 0) {
    switch (dialect) {
      case 'dameng': config.port = 5236; break;
      case 'kingbase': config.port = 54321; break;
      case 'postgres': config.port = 5432; break;
      default: config.port = 0; break; // sqlite 不需要端口
    }
  }

  return config;
}

/**
 * SQL 方言翻译器
 * 将标准 SQL 翻译为各数据库方言的 SQL
 */
export class SqlDialectTranslator {
  private dialect: DbDialect;

  constructor(dialect: DbDialect) {
    this.dialect = dialect;
  }

  /**
   * 翻译建表语句
   */
  translateCreateTable(sql: string): string {
    if (this.dialect === 'sqlite') return sql;

    let translated = sql;

    // SQLite → 达梦/金仓 常见差异
    translated = translated.replace(/INTEGER PRIMARY KEY AUTOINCREMENT/gi, 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
    translated = translated.replace(/TEXT/gi, 'VARCHAR2(4000)');
    translated = translated.replace(/DATETIME DEFAULT CURRENT_TIMESTAMP/gi, 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP');
    translated = translated.replace(/BLOB/gi, 'BLOB');

    // 达梦特殊处理
    if (this.dialect === 'dameng') {
      translated = translated.replace(/IF NOT EXISTS/gi, '');
      translated = translated.replace(/BOOLEAN/gi, 'NUMBER(1)');
      translated = translated.replace(/DOUBLE/gi, 'NUMBER');
    }

    // 金仓特殊处理
    if (this.dialect === 'kingbase') {
      translated = translated.replace(/BOOLEAN/gi, 'BOOLEAN');
      translated = translated.replace(/DOUBLE/gi, 'DOUBLE PRECISION');
    }

    return translated;
  }

  /**
   * 获取参数占位符
   * SQLite: ?, ?, ?
   * 达梦: :1, :2, :3
   * 金仓: $1, $2, $3
   */
  getPlaceholder(index: number): string {
    switch (this.dialect) {
      case 'dameng': return `:${index}`;
      case 'kingbase':
      case 'postgres': return `$${index}`;
      default: return '?';
    }
  }

  /**
   * 翻译分页查询
   */
  translateLimit(sql: string, limit: number, offset: number): string {
    switch (this.dialect) {
      case 'dameng':
        return `SELECT * FROM (SELECT TMP.*, ROWNUM ROW_ID FROM (${sql}) TMP WHERE ROWNUM <= ${offset + limit}) WHERE ROW_ID > ${offset}`;
      case 'kingbase':
      case 'postgres':
        return `${sql} LIMIT ${limit} OFFSET ${offset}`;
      default:
        return `${sql} LIMIT ${limit} OFFSET ${offset}`;
    }
  }

  /**
   * 翻译 LIKE 查询（达梦默认大小写敏感）
   */
  translateLike(column: string, pattern: string): string {
    if (this.dialect === 'dameng') {
      return `UPPER(${column}) LIKE UPPER('${pattern}')`;
    }
    return `${column} LIKE '${pattern}'`;
  }

  /**
   * 获取当前时间函数
   */
  getNowFunction(): string {
    switch (this.dialect) {
      case 'dameng': return 'SYSDATE';
      case 'kingbase':
      case 'postgres': return 'NOW()';
      default: return "datetime('now','localtime')";
    }
  }

  /**
   * 获取自增ID函数
   */
  getLastInsertIdFunction(tableName: string, columnName: string): string {
    switch (this.dialect) {
      case 'dameng':
        return `SELECT ${columnName}_SEQ.CURRVAL FROM DUAL`;
      case 'kingbase':
      case 'postgres':
        return `SELECT CURRVAL('${tableName}_${columnName}_seq')`;
      default:
        return 'SELECT last_insert_rowid()';
    }
  }

  /**
   * 转义标识符
   */
  escapeIdentifier(name: string): string {
    switch (this.dialect) {
      case 'dameng':
      case 'kingbase':
      case 'postgres':
        return `"${name}"`;
      default:
        return `"${name}"`;
    }
  }

  /**
   * 翻译 UPSERT 语句
   */
  translateUpsert(table: string, columns: string[], values: string[], conflictColumns: string[]): string {
    const colStr = columns.join(', ');
    const valStr = values.join(', ');

    switch (this.dialect) {
      case 'dameng':
        // 达梦使用 MERGE INTO
        return `
          MERGE INTO ${table} t
          USING (SELECT ${valStr} FROM DUAL) s
          ON (${conflictColumns.map(c => `t.${c} = s.${c}`).join(' AND ')})
          WHEN MATCHED THEN UPDATE SET ${columns.filter(c => !conflictColumns.includes(c)).map(c => `${c} = s.${c}`).join(', ')}
          WHEN NOT MATCHED THEN INSERT (${colStr}) VALUES (${valStr})
        `;
      case 'kingbase':
      case 'postgres':
        return `INSERT INTO ${table} (${colStr}) VALUES (${valStr}) ON CONFLICT (${conflictColumns.join(', ')}) DO UPDATE SET ${columns.filter(c => !conflictColumns.includes(c)).map(c => `${c} = EXCLUDED.${c}`).join(', ')}`;
      default:
        return `INSERT OR REPLACE INTO ${table} (${colStr}) VALUES (${valStr})`;
    }
  }
}

/**
 * 数据库适配器工厂
 * 根据配置创建对应的数据库适配器实例
 */
export async function createDbAdapter(config: DbAdapterConfig): Promise<DbAdapter> {
  switch (config.dialect) {
    case 'sqlite':
      // 使用现有 sql.js 实现，不引入新的适配器
      const { SqliteAdapter } = await import('./db-adapter-sqlite');
      return new SqliteAdapter(config);
    case 'dameng':
      const { DamengAdapter } = await import('./db-adapter-dameng');
      return new DamengAdapter(config);
    case 'kingbase':
      const { KingbaseAdapter } = await import('./db-adapter-kingbase');
      return new KingbaseAdapter(config);
    case 'postgres':
      const { PostgresAdapter } = await import('./db-adapter-postgres');
      return new PostgresAdapter(config);
    default:
      throw new Error(`Unsupported database dialect: ${config.dialect}`);
  }
}

/**
 * 生成数据库初始化 SQL（根据方言）
 */
export function generateInitSql(dialect: DbDialect): string {
  const t = new SqlDialectTranslator(dialect);

  // 基础表结构（V4.1 - V4.5 所有变更）
  const tables = [
    // 用户与认证
    `CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      tenant_id INTEGER DEFAULT 1,
      username TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      display_name TEXT,
      role TEXT DEFAULT 'employee',
      avatar_url TEXT,
      is_active INTEGER DEFAULT 1,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,

    // 员工
    `CREATE TABLE IF NOT EXISTS employees (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      tenant_id INTEGER DEFAULT 1,
      user_id INTEGER,
      name TEXT NOT NULL,
      department TEXT,
      position TEXT,
      email TEXT,
      phone TEXT,
      employee_code TEXT UNIQUE,
      is_ai INTEGER DEFAULT 0,
      ai_persona TEXT,
      ai_model TEXT,
      manager_id INTEGER,
      status TEXT DEFAULT 'active',
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,

    // 任务
    `CREATE TABLE IF NOT EXISTS tasks (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      tenant_id INTEGER DEFAULT 1,
      title TEXT NOT NULL,
      description TEXT,
      status TEXT DEFAULT 'pending',
      priority TEXT DEFAULT 'medium',
      assignee_id INTEGER,
      creator_id INTEGER,
      due_date DATETIME,
      completed_at DATETIME,
      parent_task_id INTEGER,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,

    // 系统设置
    `CREATE TABLE IF NOT EXISTS settings (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      tenant_id INTEGER DEFAULT 1,
      key TEXT NOT NULL,
      value TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,

    // V4.5: 迁移记录表
    `CREATE TABLE IF NOT EXISTS schema_migrations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      version TEXT NOT NULL UNIQUE,
      description TEXT,
      applied_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      checksum TEXT
    )`,
  ];

  return tables.map(sql => t.translateCreateTable(sql)).join(';\n\n') + ';';
}

/**
 * 检测当前数据库方言
 * 启动时根据环境变量和可用驱动自动选择
 */
export async function detectDialect(): Promise<DbDialect> {
  const dialect = (process.env.DB_DIALECT || 'sqlite') as DbDialect;

  // 检查驱动是否可用
  if (dialect !== 'sqlite') {
    try {
      switch (dialect) {
        case 'dameng':
          require.resolve('dmdb');
          break;
        case 'kingbase':
          require.resolve('pg'); // Kingbase V9 uses PG wire-protocol
          break;
        case 'postgres':
          require.resolve('pg');
          break;
      }
    } catch {
      console.warn(`[DB-Adapter] ${dialect} driver not found, falling back to sqlite`);
      return 'sqlite';
    }
  }

  return dialect;
}
