/** Locale-owned knowledge page copy. */
export const en = {
  title:'Knowledge',intro:'Mount local folders for extraction and model distillation, or connect read-only cloud libraries.',addLocal:'Mount local folder',addCloud:'Connect cloud library',all:'All',local:'Local',cloud:'Cloud',search:'Search mounted knowledge',sources:'Sources',documents:'Documents',ready:'Ready',needsModel:'Waiting for model',empty:'No knowledge sources match this view.',open:'Open',source:'Source folder',browse:'Browse…',precheck:'Check folder',checked:'Folder is readable. Source files will stay unchanged.',artifactRoot:'Application artifact directory',modelPlan:'Model plan',modelPlanValue:'Measure installed Ollama models and use the fastest responding model. If none responds, extracted text is retained and clearly marked.',mountScan:'Mount and start',cancel:'Cancel',close:'Close',imaTitle:'Connect ima',imaHelp:'XYAI reads ima file metadata here. File content is searched remotely only when a conversation calls the knowledge tool.',clientId:'Client ID',apiKey:'API Key',testConnection:'Test connection',knowledgeBase:'Knowledge base',displayName:'Display name',connect:'Connect',connected:'Connection succeeded. Select a visible library.',noCloudLibraries:'Connection succeeded, but this account returned no visible knowledge libraries.',back:'Back to knowledge',rescan:'Rescan and distill',retry:'Retry unfinished',refreshCloud:'Refresh cloud list',rename:'Rename',save:'Save',detach:'Detach',detachConfirm:'Detach this source?',detachLocalNote:'The registration is removed. Original files and application artifacts are retained.',detachCloudNote:'The registration and stored credentials are removed. Cloud files are unchanged.',fileList:'File list',folderTree:'Folders',parent:'Parent',path:'Path',status:'Status',characters:'Characters',model:'Model',preview:'Extracted text',semantic:'Semantic artifact',noPreview:'Select a local document to preview.',cloudReadonly:'Cloud metadata only. XYAI does not download or parse these files; knowledge_search queries ima during a conversation.',refreshing:'Working…',processed:'Processed',error:'Error',loading:'Loading…',selectCurrent:'Select this folder',pickerTitle:'Select local knowledge folder',folder:'Folder',lastUpdated:'Last updated',measured:'Measured',notMeasured:'No responding local model measured',extracted:'Extracted',distilling:'Distilling',failed:'Failed',delete:'Confirm detach',filterFiles:'Filter files',noFiles:'No files are available.',outputDir:'Parse output directory',outputBrowse:'Choose output…',outputDefault:'Use application default',outputHint:'Extracted text and semantic artifacts are written here. The source folder stays read-only.',outputPickerTitle:'Select parse output folder',root:'Root',cloudRoot:'Library root',cloudBack:'Back one level',type:'Type',cloudFolder:'Folder',cloudFile:'File'
} as const
/** Typed Client dictionary key. */
export type Key = keyof typeof en
/** Chinese dictionary mirrors the English key set. */
export const zh: Record<Key,string> = {
  title:'知识库',intro:'挂接本地文件夹进行抽取与模型蒸馏，或连接只读云知识库。',addLocal:'挂接本地文件夹',addCloud:'连接云知识库',all:'全部',local:'本地',cloud:'云端',search:'搜索已挂接知识库',sources:'知识库',documents:'文件',ready:'可用',needsModel:'等待本地模型',empty:'当前条件下没有知识库。',open:'打开',source:'本地资料文件夹',browse:'浏览…',precheck:'检查文件夹',checked:'文件夹可读取。原始文件及目录不会被改动。',artifactRoot:'应用解析产物目录',modelPlan:'本地模型安排',modelPlanValue:'实测已安装的 Ollama 模型并选择响应最快者；没有模型响应时保留抽取文本并明确标为等待模型。',mountScan:'挂接并开始处理',cancel:'取消',close:'关闭',imaTitle:'连接 ima 知识库',imaHelp:'此处只读取 ima 文件元数据；仅当对话调用知识库工具时，才远程检索内容片段。',clientId:'Client ID',apiKey:'API Key',testConnection:'测试连接',knowledgeBase:'选择知识库',displayName:'显示名称',connect:'完成挂接',connected:'连接成功，请选择可见知识库。',noCloudLibraries:'连接成功，但此账号没有返回可见知识库。',back:'返回知识库',rescan:'重新扫描并蒸馏',retry:'重试未完成项',refreshCloud:'刷新云端清单',rename:'重命名',save:'保存',detach:'解除挂接',detachConfirm:'确定解除此知识库？',detachLocalNote:'仅删除挂接登记；原文件和应用解析产物均保留。',detachCloudNote:'删除挂接登记及对应凭据；云端文件不受影响。',fileList:'文件列表',folderTree:'文件夹',parent:'上一级',path:'路径',status:'状态',characters:'字符数',model:'模型',preview:'抽取文本',semantic:'语义蒸馏结果',noPreview:'请选择本地文件查看结果。',cloudReadonly:'这里只显示云端元数据，不下载、不在本机解析；对话中的 knowledge_search 会按需调用 ima。',refreshing:'正在处理…',processed:'已处理',error:'错误',loading:'正在加载…',selectCurrent:'选择当前文件夹',pickerTitle:'选择本地知识库文件夹',folder:'文件夹',lastUpdated:'最近更新',measured:'实测',notMeasured:'尚未测得可响应的本地模型',extracted:'已抽取，待模型',distilling:'正在蒸馏',failed:'失败',delete:'确认解除',filterFiles:'筛选文件',noFiles:'暂无文件。',outputDir:'解析输出目录',outputBrowse:'选择输出目录…',outputDefault:'使用应用默认目录',outputHint:'抽取文本与语义产物写到这里。源文件夹保持只读，不会被改写。',outputPickerTitle:'选择解析输出目录',root:'根目录',cloudRoot:'知识库根目录',cloudBack:'返回上一级',type:'类型',cloudFolder:'文件夹',cloudFile:'文件'
}
