/** Knowledge management UI backed exclusively by Host operations. */
import React, { useEffect, useMemo, useState } from 'react'
import type { CloudDocumentRecord, CloudMount, LocalMount, Mount, Snapshot, TreeEntry } from '../protocol.ts'
import type { Key } from './locales.ts'
import './knowledge.css'

/** Typed provider call supplied by the Client plugin. */
export type Call = <T>(endpoint: string, payload?: unknown) => Promise<T>
/** One Host directory row returned by DSH's browse capability. */
export interface DirectoryEntry { name: string; path: string; hidden: boolean }
/** One Host directory listing. */
export interface DirectoryListing { path: string; home: string; crumbs: DirectoryEntry[]; entries: DirectoryEntry[]; truncated: boolean }

type Dialog = 'local' | 'ima' | 'detach' | null
const empty: Snapshot = { mounts: [], busy: null, processed: 0, error: null, artifactRoot: '' }

/** Render complete local and cloud knowledge workflows. */
export function KnowledgePage({ call, t, listDirectory }: { call: Call; t: (key: Key) => string; listDirectory: (path?: string) => Promise<DirectoryListing> }): React.ReactElement {
  const [snapshot, setSnapshot] = useState<Snapshot>(empty)
  const [loaded, setLoaded] = useState(false); const [error, setError] = useState(''); const [pending, setPending] = useState(false)
  const [tab, setTab] = useState<'all'|'local'|'cloud'>('all'); const [search, setSearch] = useState(''); const [selected, setSelected] = useState<string|null>(null); const [dialog, setDialog] = useState<Dialog>(null)
  const [source, setSource] = useState(''); const [checked, setChecked] = useState(''); const [picker, setPicker] = useState<DirectoryListing|null>(null); const [output, setOutput] = useState(''); const [outputPicker, setOutputPicker] = useState<DirectoryListing|null>(null)
  const [clientId, setClientId] = useState(''); const [apiKey, setApiKey] = useState(''); const [libraries, setLibraries] = useState<Array<{id:string;name:string}>>([]); const [connectionTested, setConnectionTested] = useState(false); const [libraryId, setLibraryId] = useState(''); const [cloudName, setCloudName] = useState('')
  const [tree, setTree] = useState<TreeEntry[]>([]); const [treePath, setTreePath] = useState(''); const [fileSearch, setFileSearch] = useState(''); const [preview, setPreview] = useState(''); const [previewMode, setPreviewMode] = useState<'text'|'semantic'>('text'); const [name, setName] = useState('')
  const [cloudDocs, setCloudDocs] = useState<CloudDocumentRecord[]>([]); const [cloudStack, setCloudStack] = useState<Array<{id:string;title:string}>>([])

  const refresh = async (): Promise<void> => { const value = await call<Snapshot>('snapshot'); setSnapshot(value); setLoaded(true) }
  useEffect(() => { let alive = true; let timer: ReturnType<typeof setTimeout>; const poll = async (): Promise<void> => { try { const value = await call<Snapshot>('snapshot'); if (alive) { setSnapshot(value); setLoaded(true) } } catch (cause) { if (alive) setError(cause instanceof Error ? cause.message : String(cause)) } finally { if (alive) timer = setTimeout(() => void poll(), 1_000) } }; void poll(); return () => { alive = false; clearTimeout(timer) } }, [call])
  const run = async (operation: () => Promise<void>): Promise<void> => { setPending(true); setError(''); try { await operation(); await refresh() } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } finally { setPending(false) } }
  const mount = snapshot.mounts.find(item => item.id === selected)
  const filtered = useMemo(() => snapshot.mounts.filter(item => (tab === 'all' || (tab === 'local' ? item.kind === 'local' : item.kind === 'ima')) && (item.name + (item.kind === 'local' ? item.root : item.knowledgeBaseId)).toLocaleLowerCase().includes(search.toLocaleLowerCase())), [snapshot.mounts, tab, search])
  const localDocs = mount?.kind === 'local' ? mount.documents.filter(item => item.path.toLocaleLowerCase().includes(fileSearch.toLocaleLowerCase())) : []
  const ready = snapshot.mounts.reduce((count, item) => count + (item.kind === 'local' ? item.documents.filter(doc => doc.state === 'ready').length : item.documents.length), 0)
  const waiting = snapshot.mounts.reduce((count, item) => count + (item.kind === 'local' ? item.documents.filter(doc => doc.state === 'extracted' || doc.state === 'distilling').length : 0), 0)
  const openMount = (item: Mount): void => { setSelected(item.id); setName(item.name); setPreview(''); setTree([]); setTreePath(''); setFileSearch(''); setCloudDocs(item.kind === 'ima' ? item.documents : []); setCloudStack([]) }
  const browseTree = async (path: string): Promise<void> => { if (mount?.kind !== 'local') return; await run(async () => { setTree(await call<TreeEntry[]>('tree', { id: mount.id, path })); setTreePath(path) }) }
  const showPreview = async (documentId: string, mode: 'text'|'semantic'): Promise<void> => { if (mount?.kind !== 'local') return; await run(async () => { setPreviewMode(mode); setPreview(await call<string>('preview', { id: mount.id, documentId, view: mode })) }) }
  const browseCloud = async (stack: Array<{id:string;title:string}>): Promise<void> => { if (mount?.kind !== 'ima') return; await run(async () => { const folderId = stack.at(-1)?.id; setCloudDocs(await call<CloudDocumentRecord[]>('cloudList', { id: mount.id, ...(folderId ? { folderId } : {}) })); setCloudStack(stack) }) }
  const refreshCloud = async (): Promise<void> => { if (mount?.kind !== 'ima') return; await run(async () => { await call('refreshIma', { id: mount.id }); setCloudDocs(await call<CloudDocumentRecord[]>('cloudList', { id: mount.id })); setCloudStack([]) }) }
  const stateLabel = (state: LocalMount['documents'][number]['state']): string => state === 'ready' ? t('ready') : state === 'extracted' ? t('extracted') : state === 'distilling' ? t('distilling') : t('failed')
  const closeDialog = (): void => { setDialog(null); setPicker(null); setOutputPicker(null) }

  if (mount !== undefined) return <section className="xyai-kb"><div className="xyai-kb__detail">
    <button onClick={() => setSelected(null)}>← {t('back')}</button>
    {(error||snapshot.error)&&<div role="alert" className="xyai-kb__alert">{t('error')}: {error||snapshot.error}</div>}
    <div className="xyai-kb__panel"><div className="xyai-kb__cardhead"><div><h1>{mount.name}</h1><p>{mount.kind === 'local' ? mount.root : `ima · ${mount.knowledgeBaseId}`}</p></div><span className={`xyai-kb__kind ${mount.kind === 'ima' ? 'cloud':''}`}>{t(mount.kind === 'local' ? 'local':'cloud')}</span></div>
      <div className="xyai-kb__row"><input aria-label={t('displayName')} value={name} onChange={event => setName(event.target.value)}/><button disabled={pending || !name.trim()} onClick={() => void run(() => call('rename',{id:mount.id,name}))}>{t('save')}</button><button className="xyai-kb__danger" onClick={() => setDialog('detach')}>{t('detach')}</button></div>
      {mount.kind === 'local' ? <><p>{t('artifactRoot')}: {mount.output}</p><p>{t('model')}: {mount.selectedModel ? `${mount.selectedModel.name} · ${mount.selectedModel.tokensPerSecond?.toFixed(1) ?? '?'} tok/s · ${t('measured')}` : t('notMeasured')}</p><div className="xyai-kb__row"><button className="primary" disabled={pending || snapshot.busy !== null} onClick={() => void run(() => call('scan',{id:mount.id}))}>{t('rescan')}</button><button disabled={pending || snapshot.busy !== null} onClick={() => void run(() => call('retry',{id:mount.id}))}>{t('retry')}</button></div></> : <><p className="xyai-kb__hint">{t('cloudReadonly')}</p><button className="primary" disabled={pending} onClick={() => void refreshCloud()}>{t('refreshCloud')}</button></>}
    </div>
    {mount.kind === 'local' ? <div className="xyai-kb__split"><div className="xyai-kb__panel xyai-kb__tree"><h3>{t('folderTree')}</h3><button onClick={() => void browseTree('')}>{t('root')}</button>{treePath && <button onClick={() => void browseTree(treePath.split(/[\\/]/).slice(0,-1).join('/'))}>↑ {t('parent')}</button>}{tree.filter(item=>item.directory).map(item=><button key={item.path} onClick={() => void browseTree(item.path)}>📁 {item.name}</button>)}</div><div className="xyai-kb__panel"><div className="xyai-kb__cardhead"><h3>{t('fileList')}</h3><input className="xyai-kb__search" aria-label={t('filterFiles')} placeholder={t('filterFiles')} value={fileSearch} onChange={event=>setFileSearch(event.target.value)}/></div><table><thead><tr><th>{t('path')}</th><th>{t('status')}</th><th>{t('characters')}</th><th></th></tr></thead><tbody>{localDocs.map(doc=><tr key={doc.id}><td>{doc.path}{doc.error && <small className="xyai-kb__danger"><br/>{doc.error}</small>}</td><td><span className={`xyai-kb__status ${doc.state}`}>{stateLabel(doc.state)}</span></td><td>{doc.characters}</td><td><button disabled={doc.state==='failed'} onClick={() => void showPreview(doc.id,'text')}>{t('preview')}</button>{doc.state==='ready' && <button onClick={() => void showPreview(doc.id,'semantic')}>{t('semantic')}</button>}</td></tr>)}</tbody></table>{localDocs.length===0&&<p>{t('noFiles')}</p>}{preview&&<><h3>{t(previewMode==='text'?'preview':'semantic')}</h3><pre className="xyai-kb__preview">{preview}</pre></>}</div></div> : <div className="xyai-kb__panel"><div className="xyai-kb__cardhead"><h3>{t('fileList')} ({cloudDocs.length})</h3><div className="xyai-kb__row"><button disabled={pending || cloudStack.length === 0} onClick={() => void browseCloud(cloudStack.slice(0,-1))}>↑ {t('cloudBack')}</button><button disabled={pending || cloudStack.length === 0} onClick={() => void browseCloud([])}>{t('cloudRoot')}</button></div></div><p className="xyai-kb__hint">{t('cloudRoot')}{cloudStack.map(item => ` / ${item.title}`).join('')}</p><table><thead><tr><th>{t('documents')}</th><th>{t('type')}</th><th>ID</th></tr></thead><tbody>{cloudDocs.map(doc=><tr key={doc.id}><td>{doc.directory ? <button disabled={pending} onClick={() => void browseCloud([...cloudStack,{id:doc.id,title:doc.title}])}>📁 {doc.title}</button> : <>📄 {doc.title}</>}</td><td>{t(doc.directory ? 'cloudFolder':'cloudFile')}</td><td>{doc.id}</td></tr>)}</tbody></table>{cloudDocs.length===0&&<p>{t('noFiles')}</p>}</div>}
    {dialog==='detach'&&<div className="xyai-kb__dialogbg"><div className="xyai-kb__dialog" role="dialog" aria-label={t('detachConfirm')}><h2>{t('detachConfirm')}</h2><p>{t(mount.kind==='local'?'detachLocalNote':'detachCloudNote')}</p><div className="xyai-kb__row"><button onClick={closeDialog}>{t('cancel')}</button><button className="primary" onClick={() => void run(async()=>{await call('unmount',{id:mount.id});setSelected(null);closeDialog()})}>{t('delete')}</button></div></div></div>}
  </div></section>

  return <section className="xyai-kb"><header className="xyai-kb__head"><div><h1>{t('title')}</h1><p>{t('intro')}</p></div><div className="xyai-kb__actions"><button onClick={()=>setDialog('ima')}>{t('addCloud')}</button><button className="primary" onClick={()=>setDialog('local')}>{t('addLocal')}</button></div></header>
    {(error||snapshot.error)&&<div role="alert" className="xyai-kb__alert">{t('error')}: {error||snapshot.error}</div>}{snapshot.busy&&<div role="status" className="xyai-kb__busy">{t('refreshing')} · {t('processed')} {snapshot.processed}</div>}{!loaded&&<div role="status" className="xyai-kb__busy">{t('loading')}</div>}
    <div className="xyai-kb__stats"><div className="xyai-kb__stat"><strong>{snapshot.mounts.length}</strong>{t('sources')}</div><div className="xyai-kb__stat"><strong>{snapshot.mounts.reduce((n,m)=>n+m.documents.length,0)}</strong>{t('documents')}</div><div className="xyai-kb__stat"><strong>{ready}</strong>{t('ready')}</div><div className="xyai-kb__stat"><strong>{waiting}</strong>{t('needsModel')}</div></div>
    <div className="xyai-kb__toolbar"><div className="xyai-kb__tabs">{(['all','local','cloud'] as const).map(value=><button key={value} className={tab===value?'active':''} onClick={()=>setTab(value)}>{t(value)}</button>)}</div><input className="xyai-kb__search" aria-label={t('search')} placeholder={t('search')} value={search} onChange={event=>setSearch(event.target.value)}/></div>
    <div className="xyai-kb__grid">{filtered.map(item=><button className="xyai-kb__card" key={item.id} onClick={()=>openMount(item)}><div className="xyai-kb__cardhead"><strong>{item.name}</strong><span className={`xyai-kb__kind ${item.kind==='ima'?'cloud':''}`}>{t(item.kind==='local'?'local':'cloud')}</span></div><p className="xyai-kb__meta">{item.kind==='local'?item.root:item.knowledgeBaseId}</p><p>{t('documents')} {item.documents.length} · {item.kind==='local'&&item.documents.some(doc=>doc.state==='extracted')?t('needsModel'):t('ready')}</p></button>)}{filtered.length===0&&<div className="xyai-kb__empty">{t('empty')}</div>}</div>
    {dialog==='local'&&<div className="xyai-kb__dialogbg"><div className="xyai-kb__dialog" role="dialog" aria-label={t('addLocal')}><h2>{t('addLocal')}</h2><label className="xyai-kb__field"><span>{t('source')}</span><div className="xyai-kb__row"><input value={source} onChange={event=>{setSource(event.target.value);setChecked('')}}/><button onClick={()=>void run(async()=>setPicker(await listDirectory(source||undefined)))}>{t('browse')}</button></div></label>{picker&&<div className="xyai-kb__picker xyai-kb__hint"><strong>{t('pickerTitle')}</strong><span>{picker.path}</span>{picker.entries.map(entry=><button key={entry.path} onClick={()=>void run(async()=>setPicker(await listDirectory(entry.path)))}>📁 {entry.name}</button>)}<button className="primary" onClick={()=>{setSource(picker.path);setChecked('');setPicker(null)}}>{t('selectCurrent')}</button></div>}<button disabled={pending||!source.trim()} onClick={()=>void run(async()=>{const result=await call<{root:string;existing:string|null}>('precheck',{path:source});if(result.existing)throw new Error('ALREADY_MOUNTED');setChecked(result.root)})}>{t('precheck')}</button>{checked&&<><p className="xyai-kb__hint">✓ {t('checked')}</p><label className="xyai-kb__field"><span>{t('outputDir')}</span><div className="xyai-kb__row"><input aria-label={t('outputDir')} value={output} placeholder={snapshot.artifactRoot} onChange={event=>setOutput(event.target.value)}/><button type="button" onClick={()=>void run(async()=>setOutputPicker(await listDirectory(output||snapshot.artifactRoot||undefined)))}>{t('outputBrowse')}</button><button type="button" onClick={()=>setOutput('')}>{t('outputDefault')}</button></div></label><p className="xyai-kb__hint">{t('outputHint')}</p>{outputPicker&&<div className="xyai-kb__picker xyai-kb__hint"><strong>{t('outputPickerTitle')}</strong><span>{outputPicker.path}</span>{outputPicker.entries.map(entry=><button key={entry.path} onClick={()=>void run(async()=>setOutputPicker(await listDirectory(entry.path)))}>📁 {entry.name}</button>)}<button className="primary" onClick={()=>{setOutput(outputPicker.path);setOutputPicker(null)}}>{t('selectCurrent')}</button></div>}<p><strong>{t('artifactRoot')}:</strong> {output.trim() || snapshot.artifactRoot}</p><p><strong>{t('modelPlan')}:</strong> {t('modelPlanValue')}</p></>}<div className="xyai-kb__row"><button onClick={closeDialog}>{t('cancel')}</button><button className="primary" disabled={!checked||pending} onClick={()=>void run(async()=>{const added=await call<LocalMount>('mountLocal',output.trim()?{path:checked,output:output.trim()}:{path:checked});await call('scan',{id:added.id});closeDialog();openMount(added)})}>{t('mountScan')}</button></div></div></div>}
    {dialog==='ima'&&<div className="xyai-kb__dialogbg"><div className="xyai-kb__dialog" role="dialog" aria-label={t('imaTitle')}><h2>{t('imaTitle')}</h2><p className="xyai-kb__hint">{t('imaHelp')}</p><label className="xyai-kb__field"><span>{t('clientId')}</span><input value={clientId} onChange={event=>{setClientId(event.target.value);setLibraries([]);setConnectionTested(false)}}/></label><label className="xyai-kb__field"><span>{t('apiKey')}</span><input type="password" value={apiKey} onChange={event=>{setApiKey(event.target.value);setLibraries([]);setConnectionTested(false)}}/></label><button disabled={pending||!clientId.trim()||!apiKey.trim()} onClick={()=>void run(async()=>{const rows=await call<Array<{id:string;name:string}>>('imaTest',{clientId,apiKey});setLibraries(rows);setConnectionTested(true);setLibraryId(rows[0]?.id??'');setCloudName(rows[0]?.name??'')})}>{t('testConnection')}</button>{connectionTested&&libraries.length===0&&<p>✓ {t('noCloudLibraries')}</p>}{libraries.length>0&&<><p>✓ {t('connected')}</p><label className="xyai-kb__field"><span>{t('knowledgeBase')}</span><select value={libraryId} onChange={event=>{setLibraryId(event.target.value);setCloudName(libraries.find(row=>row.id===event.target.value)?.name??'')}}>{libraries.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label className="xyai-kb__field"><span>{t('displayName')}</span><input value={cloudName} onChange={event=>setCloudName(event.target.value)}/></label></>}<div className="xyai-kb__row"><button onClick={closeDialog}>{t('cancel')}</button><button className="primary" disabled={pending||!libraryId||!cloudName.trim()} onClick={()=>void run(async()=>{const added=await call<CloudMount>('mountIma',{clientId,apiKey,knowledgeBaseId:libraryId,name:cloudName});setClientId('');setApiKey('');setLibraries([]);setConnectionTested(false);closeDialog();openMount(added)})}>{t('connect')}</button></div></div></div>}
  </section>
}
