export {
  inferTurnCapability,
  isToolCapability,
  type TurnCapability,
} from './infer-capability.js';
export {
  STALL_TIMEOUT_CINDY_MS,
  STALL_TIMEOUT_TOOLS_MS,
  STALL_TIMEOUT_CHAT_MS,
  stallTimeoutForCapability,
  createStallWatchdog,
  watchStall,
  type StallWatchdog,
  type StallWatchdogOptions,
} from './stall-watchdog.js';
export { RuntimeSession, type RuntimeSessionOptions } from './runtime-session.js';
export {
  normalizeGatewayCatalog,
  findCatalogEntry,
  mapCatalogProtocol,
  type CatalogLocalInput,
  type CatalogCustomProviderInput,
  type CatalogCustomModelInput,
  type CatalogBuiltinInput,
  type NormalizeGatewayCatalogInput,
} from './catalog.js';
export {
  planModelGateway,
  inferProtocolFromRef,
} from './gateway.js';
export {
  isKnowledgeSeekingQuery,
  messageHasKnowledgePrefix,
  normalizeKnowledgeHits,
  formatKnowledgePrefix,
  planKnowledgeContext,
  applyKnowledgePrefix,
  resolveKnowledgeContext,
  stubKnowledgeIngest,
  emptyKnowledgeGateway,
  KNOWLEDGE_PREFIX_RE,
  type KnowledgeSourceInput,
  type KnowledgeHitInput,
  type NormalizeKnowledgeHitsInput,
  type KnowledgeContextReason,
  type KnowledgeContextPlan,
  type PlanKnowledgeContextInput,
} from './knowledge.js';
export {
  forgePlan,
  sanitizeForgeName,
  workspaceRelForForge,
  personalizeKindForForge,
  type ForgePlan,
  type ForgePlanReason,
} from './forge.js';
export {
  indexAssetRegistry,
  createAssetRegistry,
  type AssetRegistrySnapshot,
  type AssetRegistrySourceRow,
  type AssetPromoteFn,
  type CreateAssetRegistryInput,
  type ThinAssetRegistry,
} from './registry.js';

export type {
  SessionFacade,
  PermissionMode,
  AccessMode,
  AgentKind,
  GatewayPlan,
  GatewayLift,
  NormalizedModelEntry,
  CatalogProtocol,
  CatalogSource,
  KnowledgeSourceKind,
  KnowledgeHit,
  KnowledgeQuery,
  KnowledgeGateway,
  ForgeAssetKind,
  ForgeRequest,
  ForgeResult,
  ForgeStage,
  ForgeFile,
  AssetSpace,
  AssetRegistryOrigin,
  AssetRegistryKind,
  AssetRegistryEntry,
  AssetRegistry,
  AssetRegistryListFilter,
  AssetLinkResult,
  AssetPromoteResult,
} from '@xyai/contracts';

export {
  accessModeToPermissionMode,
  permissionModeToAccessMode,
  normalizeAccessMode,
  normalizePermissionMode,
  normalizeAgentKind,
  isAgentKind,
  ACCESS_MODES,
  PERMISSION_MODES,
  AGENT_KINDS,
  FORGE_ASSET_KINDS,
  FORGE_WORKSPACE_FOLDERS,
  normalizeForgeAssetKind,
  isForgeAssetKind,
  workspaceFolderForKind,
  inferForgeKindFromWorkspaceRel,
  interopKindForForge,
  assetRegistryId,
  normalizeAssetRegistryKind,
  isAssetSpace,
  isAssetRegistryOrigin,
  ASSET_SPACES,
  ASSET_REGISTRY_ORIGINS,
} from '@xyai/contracts';
