import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const desktopRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const repositoryRoot = resolve(desktopRoot, '../..')
const main = readFileSync(resolve(desktopRoot, 'src/main.ts'), 'utf8')
const migratedClient = readFileSync(
  resolve(repositoryRoot, 'packages/client/xyai-industry-agent/lib/client.js'),
  'utf8',
)
const migratedWorkspaceHost = readFileSync(
  resolve(repositoryRoot, 'packages/client/xyai-industry-agent/lib/skill-workspace.js'),
  'utf8',
)
const migratedClientPackage = readFileSync(
  resolve(repositoryRoot, 'packages/client/xyai-industry-agent/package.json'),
  'utf8',
)
const migratedLocalGguf = readFileSync(
  resolve(repositoryRoot, 'packages/client/xyai-industry-agent/lib/local-gguf-3IBAx29M.js'),
  'utf8',
)
const dshPreload = readFileSync(resolve(desktopRoot, 'src/dsh-preload.ts'), 'utf8')
const legacyCustomization = readFileSync(resolve(desktopRoot, 'src/founders-customization.ts'), 'utf8')

describe('XYAI Founders development shell', () => {
  it('uses the migrated client as the only development sidebar owner', () => {
    expect(main).not.toContain("instrumentView('founders-sidebar'")
    expect(main).not.toContain("instrumentView('founders-panel'")
    expect(migratedClient).toContain('XYAI Founders')
    expect(migratedClient).toContain('AI生产线')
    expect(migratedClient).toContain('插件能力')
    expect(migratedClient).toContain('知识库')
    expect(migratedClient).toContain('登录 / 注册')
    expect(migratedClient).toContain('智能体定制')
  })

  it('keeps the original mature production surfaces, not replacement mockups', () => {
    expect(migratedClient).toContain('ProductionLineView')
    expect(migratedClient).toContain('KnowledgeBaseView')
    expect(migratedClient).toContain('PluginPublishingView')
    expect(migratedClient).toContain('IndustryAgentView')
    expect(migratedClient).toContain('AccountPanel')
  })

  it('allows local agent customization before XYOS account connection', () => {
    expect(migratedClient).toContain('const [step, setStep] = (0, react.useState)("wizard")')
    expect(migratedClient).not.toContain('initialAccountToken === void 0 ? "auth" : "wizard"')
    expect(migratedClient).toContain('if (api.getToken() === void 0) return;')
    expect(migratedClient).toContain('下载智能体能力包前，请先注册或登录 XYOS 账户')
    expect(migratedClient).toContain('安装智能体前，请先注册或登录 XYOS 账户')
    expect(migratedClient).toContain('window.dispatchEvent(new CustomEvent("xyai-studio:open-account"))')
    expect(migratedClient).toContain('xyai.industry-agent.guest-session.v1')
    expect(migratedClient).toContain('"x-xyai-guest-session": this.guestSession')
    expect(migratedClient).toContain('children: api.getToken() === void 0 ? "生成本机草稿能力包" : "生成智能体"')
    expect(migratedClient).not.toContain('请先登录 XYOS 账户后再进行结构化模拟运行')
  })

  it('groups extracted harness capabilities and keeps user-authored plugins live', () => {
    expect(migratedClient).toContain('const PLUGIN_CAPABILITY_CATALOG')
    expect(migratedClient).toContain('source: "DSH"')
    expect(migratedClient).toContain('source: "Codex Harness"')
    expect(migratedClient).toContain('source: "Claude Harness"')
    expect(migratedClient).toContain('@deepseek-ai/dsh-subagent-codex')
    expect(migratedClient).toContain('@deepseek-ai/dsh-subagent-claude-code')
    expect(migratedClient).toContain('我开发的插件')
    expect(migratedClient).toContain('installed.map((skill)')
  })

  it('places settings in the unified account menu and keeps workbench capability routes actionable', () => {
    expect(migratedClient).toContain('children: "系统设置"')
    expect(migratedClient).toContain('width:min(310px,calc(100vw - 16px))')
    expect(migratedClient).toContain('position:fixed!important;left:var(--xyai-account-left)!important;right:auto!important;bottom:var(--xyai-account-bottom)!important;width:var(--xyai-account-width)!important')
    expect(migratedClient).toContain('Codex-inspired account sheet: match the real sidebar, not the narrow trigger.')
    expect(migratedClient).toContain('const triggerRef = (0, react.useRef)(null)')
    expect(migratedClient).toContain('candidate.height >= innerHeight * .55')
    expect(migratedClient).toContain('"--xyai-account-width": `${width}px`')
    expect(migratedClient).toContain('.xyai-account-form input{min-width:0;box-sizing:border-box;height:40px')
    expect(migratedClient).toContain('left: 8')
    expect(migratedClient).toContain('settings.dataset.xyaiSettingsIntegrated = ""')
    expect(migratedClient).toContain('让专业经验，进化为生产力。')
    expect(dshPreload).toContain("ipcRenderer.sendSync('xyai:desktop-app-icon-data-uri')")
    expect(dshPreload).not.toContain("from 'node:fs'")
    expect(dshPreload).not.toContain("from 'node:path'")
    expect(main).toContain("ipcMain.on('xyai:desktop-app-icon-data-uri'")
    expect(migratedClient).toContain('background: var(--dsw-alias-bg-base, #ffffff);')
    expect(migratedClient).not.toContain('linear-gradient(165deg, #2b87de')
    expect(migratedClient).toContain('WORKBENCH_ICON_STYLE')
    expect(migratedClient).toContain('src: window.xyaiDesktop?.appIconDataUri || XYAI_LOGO_DATA_URI')
    expect(migratedClient).toContain('className: "xyai-home-welcome"')
    expect(migratedClient).toContain('className: "xyai-home-composer welcome"')
    expect(migratedClient).toContain('className: "xyai-home-guide welcome"')
    expect(migratedClient).toContain('本机工作区自动选择 · 标准模式')
    expect(migratedClient).not.toContain('className: "xyai-home-guide-step"')
    expect(migratedClient).toContain('className: "xyai-home-guide-card"')
    expect(migratedClient).toContain('makeButton("workbench", "工作台", openWorkbench)')
    expect(migratedClient).toContain('makeButton("knowledge", "知识库", () => {')
    expect(migratedClient).toContain('makeButton("agent", "智能体定制", () => {')
    expect(migratedClient).toContain('makeButton("model-marketplace", "模型广场", () => {')
    expect(migratedClient).toContain('aria-label": "工作台对话输入"')
    expect(migratedClient).toContain('await conversation.send(text)')
    expect(migratedClient).toContain('ctx.uiWorkspace.connectWorkspace(workspaceId)')
    expect(migratedClient).toContain('ctx.sessions.open(sessionId);\n\t\t\t\t\tnavigate("conversation");\n\t\t\t\t\tawait conversation.send(text);')
    expect(migratedClient).toContain('children: "项目（可选）"')
    expect(migratedClient).toContain('placeholder: "输入新建项目名称（想保存时再建）"')
    expect(migratedClient).toContain('children: "＋ 新建并保存为项目"')
    expect(migratedClient).not.toContain('请先在上方新建或选择一个生产项目')
    expect(migratedClient).toContain('children: "← 返回"')
    expect(migratedClient).toContain('back.textContent = "← 返回"')
    expect(migratedClient).not.toContain('返回工作台')
    expect(legacyCustomization).toContain('← 返回</button>')
    expect(legacyCustomization).not.toContain('返回工作台')
    const welcomeRenderIndex = migratedClient.indexOf('if (true /* 工作台只承担欢迎与新对话入口')
    const welcomeMarkup = migratedClient.slice(welcomeRenderIndex, welcomeRenderIndex + 6_000)
    const welcomeIndex = welcomeMarkup.indexOf('className: "xyai-home-welcome"')
    const welcomeComposerIndex = welcomeMarkup.indexOf('conversationStarter')
    const welcomeNavigationIndex = welcomeMarkup.indexOf('className: "xyai-home-guide welcome"')
    const workbenchActionIndex = migratedClient.indexOf('const openWorkbench = () =>')
    const workbenchAction = migratedClient.slice(workbenchActionIndex, workbenchActionIndex + 180)
    expect(welcomeRenderIndex).toBeGreaterThan(-1)
    expect(welcomeIndex).toBeGreaterThan(-1)
    expect(welcomeComposerIndex).toBeGreaterThan(welcomeIndex)
    expect(welcomeNavigationIndex).toBeGreaterThan(welcomeComposerIndex)
    expect(workbenchAction).toContain('navigate$2("workbench")')
    expect(workbenchAction).not.toContain('startXyaiSession')
    expect(migratedClient).toContain('"model-marketplace",\n\t\t\t\t\t\t"conversation"')
    expect(migratedClient).toContain('route !== "connectors" && route !== "knowledge" && route !== "model-marketplace" && route !== "workbench" && route !== "plugin" && /* @__PURE__ */ (0, react_jsx_runtime.jsx)(ProductionProjectBar, {})')
    expect(migratedClient).toContain('useLocalModelRuntime')
    expect(migratedClient).toContain('系统内存和显存使用情况')
    expect(migratedClient).toContain('label: "故障日志分析"')
    expect(migratedClient).toContain('访问被系统拒绝')
    for (const route of ['knowledge', 'agent', 'knowledge-line', 'plugin', 'connectors', 'model-marketplace', 'system']) {
      expect(migratedClient).toContain(`navigate("${route}")`)
    }
  })

  it('keeps the migrated local-folder asset and mounts cloud sources into the same real index path', () => {
    expect(migratedClient).toContain('type: "local-folder"')
    expect(migratedClient).toContain('children: "选择本机文件夹"')
    expect(migratedClient).toContain('"新建知识库的本机目录"')
    expect(migratedClient).toContain(': "新建并挂接本机目录"')
    expect(migratedClient).toContain('const createAndAttachFolder = async () =>')
    expect(migratedClient).toContain('placeholder: "或粘贴本机文件夹绝对路径"')
    expect(migratedClient).toContain('children: "挂接此文件夹"')
    expect(migratedClient).toContain('name: "百度网盘"')
    expect(migratedClient).toContain('name: "360 AI云盘"')
    expect(migratedClient).toContain('children: "配置并挂接云盘"')
    expect(migratedClient).toContain('"/api/xyai/knowledge-bases/cloud/credentials"')
    expect(migratedClient).toContain('"保存并挂接"')
    expect(migratedClient).toContain('window.xyaiDesktop?.pickDirectory ?? window.xyaiDesktop?.pickKnowledgeDirectory')
    expect(migratedClient).toContain('本机目录选择仅在 XYAI Studio 桌面端可用')
    expect(migratedClient).not.toContain('window.open(drive.setupUrl')
    expect(migratedWorkspaceHost).toContain('parts.length === 4 && parts[1] === "sources" && parts[3] === "tree"')
    expect(migratedWorkspaceHost).toContain('CLOUD_DRIVE_PROVIDERS')
    expect(migratedWorkspaceHost).toContain('createCloudDriveGateway')
    expect(migratedWorkspaceHost).toContain('indexExternalSource(base, source.id, `cloud://')
    expect(migratedWorkspaceHost).toContain('createLocalKnowledgeParser')
    expect(migratedWorkspaceHost).toContain('内置 GGUF 优先')
    expect(migratedWorkspaceHost).toContain('自动蒸馏记忆')
    expect(migratedWorkspaceHost).toContain('XYAI_KNOWLEDGE_INDEX_CANCELLED')
    expect(migratedWorkspaceHost).toContain('index.cancel')
    expect(migratedWorkspaceHost).toContain('正在安全停止，当前文件完成后退出')
    expect(migratedClient).toContain('"停止解析"')
    expect(migratedClient).toContain('/index-jobs/${encodeURIComponent(jobId)}/cancel')
  })

  it('keeps source switching, directory refresh and parsed-file previews inside independently scrollable panes', () => {
    expect(migratedClient).toContain('className: "xyai-kb-files-pane"')
    expect(migratedClient).toContain('className: "xyai-kb-preview-pane"')
    expect(migratedClient).toContain('children: "已挂接知识库文件列表"')
    expect(migratedClient).toContain('children: "预览区"')
    expect(migratedClient).toContain('children: "刷新目录"')
    expect(migratedClient).toContain('const renderParseableTreeBranch =')
    expect(migratedClient).toContain('className: "xyai-kb-tree-branch"')
    expect(migratedClient).toContain('file.parseable === true && file.skipReason === void 0')
    expect(migratedClient).toContain('点击文件夹展开')
    expect(migratedClient).toContain('"aria-label": "切换已挂接知识源"')
    expect(migratedClient).toContain('openPreview(base, file, sourceId)')
    expect(migratedClient).toContain('placeholder: "检索原文与蒸馏记忆…"')
    expect(migratedClient).toContain("grid-template-areas:'title title' 'meta meta' 'controls controls'")
    expect(migratedClient).toContain(".xyai-kb-files-pane,.xyai-kb-preview-pane{height:clamp(260px,calc(100vh - 460px),420px);min-height:0;overflow-y:auto")
    const previewPaneIndex = migratedClient.indexOf('className: "xyai-kb-preview-pane"')
    const searchIndex = migratedClient.indexOf('className: "xyai-kb-search"', previewPaneIndex)
    expect(previewPaneIndex).toBeGreaterThan(-1)
    expect(searchIndex).toBeGreaterThan(previewPaneIndex)
  })

  it('gives only the DSH view a guarded native directory picker and yields to real conversations', () => {
    expect(main).toContain("preload: join(DESKTOP_DIR, 'lib/dsh-preload.cjs')")
    expect(main).toContain("ipcMain.handle('xyai:pick-directory'")
    expect(main).toContain("ipcMain.handle('xyai:knowledge-pick-directory'")
    expect(main).toContain("ipcMain.handle('xyai:ensure-default-workspace'")
    expect(main).toContain("name: '@deepseek-ai/dsh-host-directory-picker-browse'")
    expect(main).toContain("if (module === 'knowledge')")
    expect(main).toContain("if (module === 'customization')")
    expect(main).toContain("if (module === 'model-marketplace')")
    expect(main).toContain("selectFoundersModule('knowledge'); void lifecycle?.showWindow()")
    expect(main).toContain('event.sender.id !== dshView.webContents.id')
    expect(migratedClient).toContain('window.xyaiDesktop?.ensureDefaultWorkspace?.()')
    expect(migratedClient).toContain('const addWorkspaceFromDesktop = async () =>')
    expect(migratedClient).toContain('label === "添加工作区"')
    expect(migratedClient).toContain('ctx.uiWorkspace.startSession(workspace.workspaceId)')
    expect(migratedClient).not.toContain('ctx.workspaces.startSession')
    expect(migratedClientPackage).toContain('@deepseek-ai/dsh-client-ui-workspace')
    expect(migratedClient).toContain('"uiWorkspace"')
    expect(migratedClient).toContain('document.addEventListener("click", interceptWorkspaceActions, true)')
    expect(migratedClient).toContain('setRoute("conversation")')
    expect(migratedClient).toContain('if (route === "conversation") return null')
  })

  it('leaves the DSH request untouched and keeps Auto worker selection in the local execution adapter', () => {
    expect(migratedLocalGguf).not.toContain('component: "harness-local-worker-routing"')
    expect(migratedLocalGguf).not.toContain('ctx.on("agent/request", async ({ agent }, next) =>')
    expect(migratedLocalGguf).toContain('const automatic = options.model === XYAI_LOCAL_AUTO_MODEL ? await selectAutomaticLocalGguf(rawMessages) : void 0')
    expect(migratedLocalGguf).toContain('const suppressToolsForAuto = automatic !== void 0 && !automatic.task.requiresTools')
    expect(migratedLocalGguf).toContain('model-benchmark-direct')
  })
})
