/** A focused, post-render enhancement for the Founders production panel.
 * It deliberately replaces only the generic Agent-line form with the historic
 * four-category, governed production contract. */
export const FOUNDERS_AGENT_ENHANCEMENT_HTML = `<script>
(function(){
  function fields(type){return {advisor:[['targetUser','服务对象'],['serviceBoundary','服务边界（含不能做什么）'],['escalationRule','人工升级规则'],['answerStructure','回答结构']],workflow:[['trigger','触发条件'],['owner','流程负责人'],['exceptionStrategy','异常与退回策略'],['retryPolicy','重试规则'],['idempotencyRule','幂等规则'],['completionSignal','完成信号']],research:[['researchQuestion','研究问题'],['timeRange','时间/样本范围'],['sourceCriteria','来源准入规则'],['metricDefinitions','指标口径'],['uncertaintyPolicy','不确定性披露规则'],['reportAudience','报告读者与用途']],team:[['objective','共同目标'],['leadRole','总负责人岗位'],['reviewerRole','独立复核岗位'],['handoffProtocol','交接协议'],['conflictProtocol','冲突处理'],['finalDeliverable','最终交付物']]}[type]||[]}
  function enhance(){
    if(typeof selectedLine==='undefined'||selectedLine!=='agent'||!state?.factory?.project)return
    const form=document.getElementById('asset-form');if(!form||form.dataset.agentEnhanced==='true')return
    const capabilities=(state.factory.assets||[]).filter(asset=>asset.line==='capability'&&asset.status==='ready');form.dataset.agentEnhanced='true'
    if(!capabilities.length){form.innerHTML='<div class="note">智能体线需要先完成一项能力资产。能力可以是已审查的 Skill/MCP 组合，不强制依赖模型训练。</div>';return}
    const draw=()=>{const type=form.querySelector('[name=productionType]')?.value||'advisor';const required=fields(type);const additional=type==='advisor'?'<label>三类案例与专家证据<textarea name="experience" required placeholder="[典型案例] 真实场景和结论\\n专家判定：已通过\\n[边界案例] 条件受限场景\\n专家判定：已通过\\n[反例] 不应回答或处理的情形\\n专家判定：已通过"></textarea></label>':type==='team'?'<label>团队成员 JSON（至少两名互补角色）<textarea name="team" required placeholder="{&quot;members&quot;:[{&quot;name&quot;:&quot;分析员&quot;,&quot;role&quot;:&quot;分析&quot;,&quot;responsibility&quot;:&quot;证据分析&quot;},{&quot;name&quot;:&quot;复核员&quot;,&quot;role&quot;:&quot;复核&quot;,&quot;responsibility&quot;:&quot;独立复核&quot;}],&quot;coordination&quot;:&quot;hybrid&quot;}"></textarea></label>':'<label>节点图 JSON（工作流至少 2 个，研究至少 5 个）<textarea name="workflow" required placeholder="{&quot;nodes&quot;:[{&quot;id&quot;:&quot;n1&quot;,&quot;title&quot;:&quot;步骤&quot;,&quot;inputSpec&quot;:&quot;输入说明&quot;,&quot;outputSpec&quot;:&quot;输出说明&quot;,&quot;acceptanceCriteria&quot;:&quot;验收说明&quot;,&quot;onFailure&quot;:&quot;失败后转人工或回退&quot;,&quot;dependsOn&quot;:[]}]}"></textarea></label>'
      form.innerHTML='<div class="note"><b>四类智能体生产工艺</b>：专业顾问、工作流自动化、研究与数据分析、多智能体团队。提交会执行历史同源质量门，而不是生成普通提示词。</div><div class="row"><label>工艺类型<select name="productionType"><option value="advisor">专业顾问</option><option value="workflow">工作流自动化</option><option value="research">研究与数据分析</option><option value="team">多智能体团队</option></select></label><label>已验收能力资产<select name="capabilityAssetId">'+capabilities.map(asset=>'<option value="'+asset.id+'">'+esc(asset.name)+'</option>').join('')+'</select></label></div><div class="row"><label>智能体名称<input name="name" required maxlength="160"></label><label>行业<input name="industry" required maxlength="160"></label></div><label>功能说明<textarea name="description" required></textarea></label>'+required.map(item=>'<label>'+item[1]+'<textarea name="spec-'+item[0]+'" required></textarea></label>').join('')+additional+'<button class="button">生成受治理的智能体蓝图</button><div id="agent-result"></div>'
      form.querySelector('[name=productionType]').value=type;form.querySelector('[name=productionType]').onchange=draw
      form.onsubmit=async event=>{event.preventDefault();const data=new FormData(form);const productionType=data.get('productionType');const productionSpec={};fields(productionType).forEach(item=>productionSpec[item[0]]=String(data.get('spec-'+item[0])||''));const result=document.getElementById('agent-result');try{await window.xyaiFounders.createFactoryAgent({projectId:state.factory.project.id,productionType,name:data.get('name'),industry:data.get('industry'),description:data.get('description'),productionSpec,experience:data.get('experience'),workflow:data.get('workflow')?JSON.parse(String(data.get('workflow'))):undefined,team:data.get('team')?JSON.parse(String(data.get('team'))):undefined,capabilityAssetId:data.get('capabilityAssetId')});result.className='success';result.textContent='智能体工艺蓝图已通过质量门并登记。'}catch(error){result.className='error';result.textContent=error.message||String(error)}}
    };draw()
  }
  window.xyaiFounders.onState(()=>setTimeout(enhance,0));setTimeout(enhance,0)
})()
</script>`
