/** XYAI-owned development navigation.  It deliberately sits above the DSH
 * runtime so a Harness upgrade cannot replace the product shell. */
export const FOUNDERS_SIDEBAR_HTML = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<style>
:root{color:#172033;background:#f8fafc;font-family:"Segoe UI","Microsoft YaHei",sans-serif}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:#f8fafc}.sidebar{height:100vh;border-right:1px solid #e6ebf3;display:flex;flex-direction:column;padding:24px 16px 18px}.brand{display:flex;align-items:center;gap:10px;padding:0 4px 22px}.brand img{width:34px;height:34px;object-fit:contain;border-radius:10px}.brand-name{font-size:18px;font-weight:760;letter-spacing:-.3px}.brand-sub{font-size:11px;color:#7a879b;margin-top:2px}.workspace{display:flex;align-items:center;gap:10px;border:1px solid #e1e7f0;background:#fff;border-radius:12px;color:#1b2940;font:inherit;padding:12px;margin-bottom:24px;cursor:pointer}.workspace:hover{border-color:#9ab7ee}.workspace .plus{width:22px;height:22px;border-radius:50%;background:#e9f1ff;color:#2f72d5;display:grid;place-items:center;font-size:18px;line-height:1}.section{font-size:12px;color:#8794a8;margin:0 8px 8px}.nav{display:grid;gap:4px}.nav button,.account{border:0;background:transparent;color:#4c5a6c;text-align:left;border-radius:10px;padding:11px 12px;font:inherit;font-size:14px;cursor:pointer;display:flex;align-items:center;gap:11px}.nav button:hover,.nav button.active{background:#eaf2ff;color:#2467c5;font-weight:650}.nav .icon{width:20px;text-align:center;font-size:17px}.badge{margin-left:auto;min-width:18px;padding:1px 6px;border-radius:10px;text-align:center;background:#eef2f7;color:#6b7a8e;font-size:11px}.active .badge{background:#d7e7ff;color:#2467c5}.spacer{flex:1}.local-note{margin:12px 4px 10px;padding:10px;border-radius:10px;background:#f0f5ff;color:#637797;font-size:11px;line-height:1.55}.account{border-top:1px solid #e6ebf3;border-radius:0;padding:15px 6px 0}.avatar{width:30px;height:30px;border-radius:9px;background:linear-gradient(135deg,#4e8df0,#7b5fd6);color:white;display:grid;place-items:center;font-weight:700}.account-detail{min-width:0}.account-title{font-weight:650;color:#24344c}.account-sub{font-size:11px;color:#8794a8;margin-top:2px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
body.dark{background:#0e141c;color:#dbe4ef}body.dark .sidebar{background:#0e141c;border-right-color:#263241}body.dark .brand-name{color:#e9eef6}body.dark .brand-sub{color:#8b9bb0}body.dark .workspace{background:#161e2a;border-color:#2c394b;color:#dbe4ef}body.dark .workspace:hover{border-color:#4d8bf0}body.dark .workspace .plus{background:#1e2c40;color:#8fb8f2}body.dark .section{color:#8b9bb0}body.dark .nav button,body.dark .account{color:#b7c5d6}body.dark .nav button:hover,body.dark .nav button.active{background:#142a45;color:#a3c4f6}body.dark .badge{background:#1b2434;color:#9aa9bd}body.dark .active .badge{background:#1e3a5f;color:#8fb8f2}body.dark .local-note{background:#131f30;color:#9aa9bd}body.dark .account{border-top-color:#263241}body.dark .account-title{color:#e9eef6}body.dark .account-sub{color:#8b9bb0}
</style></head><body><aside class="sidebar">
  <div class="brand"><img src="__LOGO__" alt="XYAI"><div><div class="brand-name">XYAI Founders</div><div class="brand-sub">可信智能开发工作台</div></div></div>
  <button class="workspace" data-module="workspace"><span class="plus">+</span><span>新会话</span></button>
  <div class="section">开发空间</div><nav class="nav">
    <button data-module="workspace" class="active"><span class="icon">▦</span>工作台<span class="badge" id="session-count">0</span></button>
    <button data-module="production"><span class="icon">⌘</span>AI 生产线<span class="badge" id="production-count">0</span></button>
    <button data-module="customization"><span class="icon">✦</span>智能体定制</button>
    <button data-module="plugins"><span class="icon">◇</span>插件能力<span class="badge" id="plugin-count">0</span></button>
    <button data-module="knowledge"><span class="icon">▤</span>知识库<span class="badge" id="knowledge-count">0</span></button>
    <button data-module="model-marketplace"><span class="icon">◉</span>模型广场</button>
  </nav>
  <div class="spacer"></div><div class="local-note">核心记录保存在本机 XYAI Studio 用户数据中；不依赖原始外部目录。</div>
  <button class="account" data-module="account"><span class="avatar" id="account-avatar">XY</span><span class="account-detail"><span class="account-title" id="account-title">登录 / 注册</span><span class="account-sub" id="account-sub">连接你的 XYOS 工作区</span></span></button>
</aside><script>
const all=Array.from(document.querySelectorAll('[data-module]'));
function pick(name){all.filter(x=>x.classList.contains('nav')===false).forEach(function(x){if(x.closest('.nav'))x.classList.toggle('active',x.dataset.module===name)});document.querySelectorAll('.nav button').forEach(function(x){x.classList.toggle('active',x.dataset.module===name)});window.xyaiFounders.selectModule(name)}
all.forEach(function(button){button.addEventListener('click',function(){pick(button.dataset.module)})});
function render(state){document.getElementById('session-count').textContent=String(state.sessions.length);document.getElementById('production-count').textContent=String(state.productionRuns.length);document.getElementById('plugin-count').textContent=String(state.agentCatalog?(state.agentCatalog.skills.length+state.agentCatalog.plugins.length):state.plugins.length);document.getElementById('knowledge-count').textContent=String(state.knowledgeAssets.length);const a=state.account;document.getElementById('account-title').textContent=a.authenticated?(a.nickname||a.email||'已登录'):'登录 / 注册';document.getElementById('account-sub').textContent=a.authenticated?'已连接 XYOS 本地工作区':'连接你的 XYOS 工作区';document.getElementById('account-avatar').textContent=a.authenticated?(a.nickname||a.email||'XY').slice(0,2).toUpperCase():'XY'}
function applyTheme(state){if(!state)return;document.body.classList.toggle('dark',!!state.dark)}
window.xyaiFounders.getState().then(render);window.xyaiFounders.onState(render);
try{if(window.xyaiFounders.getTheme)window.xyaiFounders.getTheme().then(applyTheme);if(window.xyaiFounders.onThemeChange)window.xyaiFounders.onThemeChange(applyTheme)}catch(e){}
</script></body></html>`
